spring:
  profiles: default

alfresco:
  url: "http://HOST-NAME:8011/alfresco/api/-default-/cmis/versions/1.1/atom"
  userName: 
  password: 
  connectionName: test
  fileDescption: File created from test automation
  
notification:
  email:
    recipient: 
    sender: 
    message: Client Performance liability has been updteed to next quarter!
    subject:  CP liabliaty updated  
  
mail:
  utility:
    url:  
  
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
    
    
---

spring:
  profiles: dev

alfresco:
  url: "http://HOST-NAME:8011/alfresco/api/-default-/cmis/versions/1.1/atom"
  userName: 
  password: 
  connectionName: 
  folderPath: "/CI/Test-ammar"
  fileDescption: File created from test automation
  
notification:
  email:
    recipient: 
    sender: 
    message: Client Performance liability has been updteed to next quarter!
    subject:  CP liabliaty updated  
  
mail:
  utility:
    url:   
  
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
    
    
---
